name: e_waste
description: "A new Flutter project."
publish_to: 'none' # Keeps the project private; remove if publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  lottie: ^2.3.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: medieval
      fonts:
        - asset: assets/ecobyte.ttf

  # Adding the assets section for your custom files
  assets:
    - assets/leaves.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/EcoByte.png"
  adaptive_icon_background: "#ffffff" # Background color (can be transparent)
  adaptive_icon_foreground: "assets/EcoByte.png"
