name: e_waste
description: "A new Flutter project."
publish_to: 'none' # Keeps the project private; remove if publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Adding the assets section for your custom files
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/EcoByte.png"
