name: e_waste
description: "A new Flutter project."
publish_to: 'none' # Keeps the project private; remove if publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  lottie: ^3.3.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.1.7
  webview_flutter: ^4.10.0
  google_maps_flutter: ^2.2.5
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  permission_handler: ^10.2.0
  animated_text_kit: ^4.2.1
  flip_card: ^0.5.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.2.0
  web3dart: ^2.5.0
  intl: ^0.18.0
  geocoding: ^2.0.4
  shared_preferences: ^2.2.2
  candlesticks: ^2.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  fonts:
    - family: medieval
      fonts:
        - asset: assets/ecobyte.ttf

  # Adding the assets section for your custom files
  assets:
    - .env
    - assets/leaves.json
    - assets/EcoByte.png
    - assets/ewasteBg.jpg
    - assets/recycle.json
    - assets/effects.json
    - assets/gov.json
    - assets/ewaste1.jpg
    - assets/ewaste2.jpg
    - assets/ewaste3.jpg
    - assets/cf.webp
    - assets/carbon.json
    - assets/recycled.json
    - assets/points.json
    - assets/detection.json
    - assets/recycling_facility.json
    - assets/edrives.json
    - assets/collective.json
    - assets/personal.json
    - assets/chip_tracker.abi
    - assets/ecobyteLanding.png
    - assets/dashboard.json


flutter_icons:
  android: true
  ios: true
  image_path: "assets/EcoByte.png"
  adaptive_icon_background: "#ffffff" # Background color (can be transparent)
  adaptive_icon_foreground: "assets/EcoByte.png"
