// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsCrGXJBf8fPoRtJkAjnnZKXB_1VqU8o8',
    appId: '1:77342339799:web:91c630458a9588984fb692',
    messagingSenderId: '77342339799',
    projectId: 'e-waste-453420',
    authDomain: 'e-waste-453420.firebaseapp.com',
    storageBucket: 'e-waste-453420.firebasestorage.app',
    measurementId: 'G-PB7FVZN9KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtBGrD3P6EttSl9xilVt5JjUsaenl4j00',
    appId: '1:77342339799:android:9ec66f75490cf4c24fb692',
    messagingSenderId: '77342339799',
    projectId: 'e-waste-453420',
    storageBucket: 'e-waste-453420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgASmJTyAikMx9Am5cFg2UPSp3Lny54No',
    appId: '1:77342339799:ios:daf80a73e8eb84c14fb692',
    messagingSenderId: '77342339799',
    projectId: 'e-waste-453420',
    storageBucket: 'e-waste-453420.firebasestorage.app',
    iosBundleId: 'com.example.eWaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgASmJTyAikMx9Am5cFg2UPSp3Lny54No',
    appId: '1:77342339799:ios:daf80a73e8eb84c14fb692',
    messagingSenderId: '77342339799',
    projectId: 'e-waste-453420',
    storageBucket: 'e-waste-453420.firebasestorage.app',
    iosBundleId: 'com.example.eWaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsCrGXJBf8fPoRtJkAjnnZKXB_1VqU8o8',
    appId: '1:77342339799:web:beabb9ab48c6f1f44fb692',
    messagingSenderId: '77342339799',
    projectId: 'e-waste-453420',
    authDomain: 'e-waste-453420.firebaseapp.com',
    storageBucket: 'e-waste-453420.firebasestorage.app',
    measurementId: 'G-CS28TDKJDP',
  );
}
